version: 2
jobs:
  build:
    working_directory: ~/shiro
    docker:
      - image: ubuntu:rolling
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update -qq
            apt-get install -y g++ cmake git wget ssh libmysqlclient-dev libboost-all-dev libtcmalloc-minimal4 libcurl4-openssl-dev libssl-dev
      - run:
          name: Generate CMake file
          command: |
            cmake .
      - run:
          name: Build
          command: |
            make -j2
      - store_artifacts:
          path: ~/shiro/bin/shiro
          destination: shiro

notify:
  webhooks:
    - url: http://209.97.182.162:5000/shiro/callback
