# Bancho configuration file for shiro

[server]
host = "127.0.0.1"
port = 8080
# Amount of concurrent connections the server accepts.
# Set this higher if you have more players, however also results in more RAM being used.
concurrency = 64

[permissions]
# Allow users with no roles / permissions to have supporer in-game?
default_supporter = true

[api]
key = "osu!Bancho token"

[direct]
# Shiro is a reverse proxy for using other beatmap mirrors. It does not provide it's own interface.
# mode 0 = Compatibility mode with Shirogane made by Shiro
# mode 1 = Compatibility mode with Cheesegull made by Ripple
# Shiro will always send your unique server id with each direct proxy pass. It will also additionally
# omit all user credentials in the url parameters (username and md5sum of password) to prevent data leaks.
mode = 1
base_url = "https://yozora.pw"
mirror_url = "https://storage.yozora.pw"

[integrations]
sentry = true
