# Bancho configuration file for shiro

[server]
host = "127.0.0.1"
port = 8080
# Amount of concurrent connections the server accepts.
# Set this higher if you have more players, however also results in more RAM being used.
concurrency = 64

[permissions]
# Allow users with no roles / permissions to have supporer in-game?
default_supporter = true

[api]
key = "osu!Bancho token"
